### PR TITLE
Improvements and Suggestions

### PR DESCRIPTION
**Pull request by Dearex**
Changed:

    Doesn't try to send a message if there is no message
    changed behavior from "Starting and recording fixed lenght" to "Start/Stop with button, seconds = max recording time
    added tracking of keystate to avoid continous activation when holding down key
    modules
        removed: wave, numpy
        added: soundfile, queue, timeit
    Error printing (Translation doesn't seem to work, I couldn't figure out why translator.translate didn't work - 'NoneType' object has no attribute 'group')

Probably not the best way to do this but it works as far as I can tell. Also I couldn't find if there is a GitHub-Way to do this :)

Other suggestions:

    Scroll down display automatically
    Add info for installing speech_recognition (pip install SpeechRecognition), everything else is same name as import.
    I had it quite often that the chat pops up for a moment (recognition on display was correct) but no message was sent. I guess the sleep is to short, maybe make this also a setting?

Other files unchanged, but I suggest increasing the 4 Sec due to changes mentioned above

### CODE REVIEW

**Comment by Glenomat** [comment]
Will merge pull this later. First need to understand the Code xD
New window is already done now only need to do the adjustments with the sleep length.

I dont know why the translation is not working for you, maybe need to look a little bit deeper into that.

For the Suggestions: 
I will edit the Items in the View directly so there are in total always the same Items that only get edited.
I dont know how to add the info for installing packages. Maybe this wont even be needed when using an .exe file but im not sure about that.
Like mentioned above with the UI changes the setting for the waiting sleep time is already in the UI

**Comment by Dearex** [comment]
> I dont know why the translation is not working for you, maybe need to look a little bit deeper into that.
After a bit of researching this seems to be a bug in the module that is arround for a very long time... mthere is a https://github.com/lushan88a/google_trans_new or just use a completely different translator (DeepL?)

> I will edit the Items in the View directly so there are in total always the same Items that only get edited.
Nice one

> I dont know how to add the info for installing packages. Maybe this wont even be needed when using an .exe file but im not sure about that.
Might be, i just thought about a note in the readme or sth

> Like mentioned above with the UI changes the setting for the waiting sleep time is already in the UI
Good. I did a little bit of testing and it seems like this is not a delay problem. Looks like the Game (LoL) is just not accepting the text. Maybe I am holding a special key or sth, have to do further testing.

> Would you be in for a call with Discord?
Yeah sure, maybe later today or another evening (UTC+1)

**Comment by Glenomat** [comment]
> After a bit of researching this seems to be a bug in the module that is arround for a very long time... mthere is a https://github.com/lushan88a/google_trans_new or just use a completely different translator (DeepL?)

I think i will use google_trans_new
I wanted to use DeepL but to use the free Api I would also need to add Bank Information to the DeepL account and I dont really want to add Bank info just to use the Free version

> Might be, i just thought about a note in the readme or sth

Yeah I think that would be good, i will edit it with my next Push

> Yeah sure, maybe later today or another evening (UTC+1)

I would be around at 20:00 (Garmany -> I dont know what the Timezone here is exactly xD)
I dont what would be a good way to give you my Discord (Giving it here doesn't seem like the best Idea, even when probably not a lot of ppl will read this)

**Comment by Dearex** [comment]
https://discord.gg/HdYQft5X
This is a onetime Link, hop onto my development server

**Pull request merged**
